// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaosmonkey.proto

package chaosmonkey

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	raft "github.com/kpister/raft/raft"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK    StatusCode = 0
	StatusCode_ERROR StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var StatusCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{0}
}

type Status struct {
	Ret                  StatusCode `protobuf:"varint,1,opt,name=ret,proto3,enum=chaosmonkey.StatusCode" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetRet() StatusCode {
	if m != nil {
		return m.Ret
	}
	return StatusCode_OK
}

type ConnMatrix struct {
	Rows                 []*ConnMatrix_MatRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	From                 int32                `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnMatrix) Reset()         { *m = ConnMatrix{} }
func (m *ConnMatrix) String() string { return proto.CompactTextString(m) }
func (*ConnMatrix) ProtoMessage()    {}
func (*ConnMatrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{1}
}

func (m *ConnMatrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMatrix.Unmarshal(m, b)
}
func (m *ConnMatrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMatrix.Marshal(b, m, deterministic)
}
func (m *ConnMatrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMatrix.Merge(m, src)
}
func (m *ConnMatrix) XXX_Size() int {
	return xxx_messageInfo_ConnMatrix.Size(m)
}
func (m *ConnMatrix) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMatrix.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMatrix proto.InternalMessageInfo

func (m *ConnMatrix) GetRows() []*ConnMatrix_MatRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ConnMatrix) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

type ConnMatrix_MatRow struct {
	Vals                 []float32 `protobuf:"fixed32,1,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnMatrix_MatRow) Reset()         { *m = ConnMatrix_MatRow{} }
func (m *ConnMatrix_MatRow) String() string { return proto.CompactTextString(m) }
func (*ConnMatrix_MatRow) ProtoMessage()    {}
func (*ConnMatrix_MatRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{1, 0}
}

func (m *ConnMatrix_MatRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMatrix_MatRow.Unmarshal(m, b)
}
func (m *ConnMatrix_MatRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMatrix_MatRow.Marshal(b, m, deterministic)
}
func (m *ConnMatrix_MatRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMatrix_MatRow.Merge(m, src)
}
func (m *ConnMatrix_MatRow) XXX_Size() int {
	return xxx_messageInfo_ConnMatrix_MatRow.Size(m)
}
func (m *ConnMatrix_MatRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMatrix_MatRow.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMatrix_MatRow proto.InternalMessageInfo

func (m *ConnMatrix_MatRow) GetVals() []float32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

type MatValue struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Val                  float32  `protobuf:"fixed32,3,opt,name=val,proto3" json:"val,omitempty"`
	From                 int32    `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatValue) Reset()         { *m = MatValue{} }
func (m *MatValue) String() string { return proto.CompactTextString(m) }
func (*MatValue) ProtoMessage()    {}
func (*MatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{2}
}

func (m *MatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatValue.Unmarshal(m, b)
}
func (m *MatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatValue.Marshal(b, m, deterministic)
}
func (m *MatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatValue.Merge(m, src)
}
func (m *MatValue) XXX_Size() int {
	return xxx_messageInfo_MatValue.Size(m)
}
func (m *MatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MatValue.DiscardUnknown(m)
}

var xxx_messageInfo_MatValue proto.InternalMessageInfo

func (m *MatValue) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *MatValue) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *MatValue) GetVal() float32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *MatValue) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

type EmptyMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMessage) Reset()         { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()    {}
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{3}
}

func (m *EmptyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMessage.Unmarshal(m, b)
}
func (m *EmptyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMessage.Marshal(b, m, deterministic)
}
func (m *EmptyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMessage.Merge(m, src)
}
func (m *EmptyMessage) XXX_Size() int {
	return xxx_messageInfo_EmptyMessage.Size(m)
}
func (m *EmptyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMessage proto.InternalMessageInfo

type ServerState struct {
	ID                   int32         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	State                string        `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	CurrentTerm          int32         `protobuf:"varint,3,opt,name=CurrentTerm,proto3" json:"CurrentTerm,omitempty"`
	VotedFor             int32         `protobuf:"varint,4,opt,name=VotedFor,proto3" json:"VotedFor,omitempty"`
	LeaderID             int32         `protobuf:"varint,5,opt,name=LeaderID,proto3" json:"LeaderID,omitempty"`
	CommitIndex          int32         `protobuf:"varint,6,opt,name=CommitIndex,proto3" json:"CommitIndex,omitempty"`
	LastApplied          int32         `protobuf:"varint,7,opt,name=LastApplied,proto3" json:"LastApplied,omitempty"`
	MatchIndex           []int32       `protobuf:"varint,8,rep,packed,name=MatchIndex,proto3" json:"MatchIndex,omitempty"`
	NextIndex            []int32       `protobuf:"varint,9,rep,packed,name=nextIndex,proto3" json:"nextIndex,omitempty"`
	Log                  []*raft.Entry `protobuf:"bytes,10,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ServerState) Reset()         { *m = ServerState{} }
func (m *ServerState) String() string { return proto.CompactTextString(m) }
func (*ServerState) ProtoMessage()    {}
func (*ServerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{4}
}

func (m *ServerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerState.Unmarshal(m, b)
}
func (m *ServerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerState.Marshal(b, m, deterministic)
}
func (m *ServerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerState.Merge(m, src)
}
func (m *ServerState) XXX_Size() int {
	return xxx_messageInfo_ServerState.Size(m)
}
func (m *ServerState) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerState.DiscardUnknown(m)
}

var xxx_messageInfo_ServerState proto.InternalMessageInfo

func (m *ServerState) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ServerState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ServerState) GetCurrentTerm() int32 {
	if m != nil {
		return m.CurrentTerm
	}
	return 0
}

func (m *ServerState) GetVotedFor() int32 {
	if m != nil {
		return m.VotedFor
	}
	return 0
}

func (m *ServerState) GetLeaderID() int32 {
	if m != nil {
		return m.LeaderID
	}
	return 0
}

func (m *ServerState) GetCommitIndex() int32 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *ServerState) GetLastApplied() int32 {
	if m != nil {
		return m.LastApplied
	}
	return 0
}

func (m *ServerState) GetMatchIndex() []int32 {
	if m != nil {
		return m.MatchIndex
	}
	return nil
}

func (m *ServerState) GetNextIndex() []int32 {
	if m != nil {
		return m.NextIndex
	}
	return nil
}

func (m *ServerState) GetLog() []*raft.Entry {
	if m != nil {
		return m.Log
	}
	return nil
}

func init() {
	proto.RegisterEnum("chaosmonkey.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "chaosmonkey.Status")
	proto.RegisterType((*ConnMatrix)(nil), "chaosmonkey.ConnMatrix")
	proto.RegisterType((*ConnMatrix_MatRow)(nil), "chaosmonkey.ConnMatrix.MatRow")
	proto.RegisterType((*MatValue)(nil), "chaosmonkey.MatValue")
	proto.RegisterType((*EmptyMessage)(nil), "chaosmonkey.EmptyMessage")
	proto.RegisterType((*ServerState)(nil), "chaosmonkey.ServerState")
}

func init() { proto.RegisterFile("chaosmonkey.proto", fileDescriptor_3ee19988c9499698) }

var fileDescriptor_3ee19988c9499698 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdd, 0x6a, 0xdb, 0x40,
	0x10, 0x85, 0x23, 0xc9, 0x72, 0xed, 0x51, 0x30, 0xee, 0xb6, 0x25, 0xaa, 0x49, 0x53, 0xa1, 0x9b,
	0xba, 0xbd, 0x70, 0xc0, 0xb9, 0x2c, 0x14, 0x82, 0xed, 0x16, 0xd3, 0x88, 0xc0, 0xe6, 0xe7, 0x7e,
	0x63, 0x4d, 0x6c, 0x11, 0x49, 0x2b, 0x56, 0xeb, 0xbf, 0x97, 0xea, 0x9b, 0xf4, 0x9d, 0xca, 0xee,
	0x2a, 0x91, 0x0c, 0xcd, 0x8d, 0x98, 0x3d, 0x73, 0x66, 0x8e, 0xc4, 0x7e, 0x82, 0xb7, 0x8b, 0x15,
	0xe3, 0x65, 0xc6, 0xf3, 0x27, 0xdc, 0x8f, 0x0a, 0xc1, 0x25, 0x27, 0x5e, 0x43, 0x1a, 0x7c, 0x59,
	0x26, 0x72, 0xb5, 0x7e, 0x18, 0x2d, 0x78, 0x76, 0xfe, 0x54, 0x24, 0xa5, 0x44, 0x71, 0x2e, 0xd8,
	0xa3, 0xac, 0x1f, 0x66, 0x2a, 0xbc, 0x80, 0xf6, 0x8d, 0x64, 0x72, 0x5d, 0x92, 0xaf, 0xe0, 0x08,
	0x94, 0xbe, 0x15, 0x58, 0xc3, 0xde, 0xf8, 0x64, 0xd4, 0x0c, 0x30, 0x8e, 0x09, 0x8f, 0x91, 0x2a,
	0x4f, 0x28, 0x00, 0x26, 0x3c, 0xcf, 0x23, 0x26, 0x45, 0xb2, 0x23, 0x63, 0x68, 0x09, 0xbe, 0x2d,
	0x7d, 0x2b, 0x70, 0x86, 0xde, 0xf8, 0xec, 0x60, 0xb2, 0xb6, 0x8d, 0x22, 0x26, 0x29, 0xdf, 0x52,
	0xed, 0x25, 0x04, 0x5a, 0x8f, 0x82, 0x67, 0xbe, 0x1d, 0x58, 0x43, 0x97, 0xea, 0x7a, 0x70, 0x0a,
	0x6d, 0xe3, 0x51, 0xdd, 0x0d, 0x4b, 0xcd, 0x46, 0x9b, 0xea, 0x3a, 0xbc, 0x85, 0x4e, 0xc4, 0xe4,
	0x3d, 0x4b, 0xd7, 0x48, 0xfa, 0xe0, 0x08, 0xbe, 0xd5, 0xaf, 0xea, 0x52, 0x55, 0x2a, 0x65, 0xc1,
	0xd3, 0x6a, 0x9d, 0x2a, 0x95, 0xb2, 0x61, 0xa9, 0xef, 0x04, 0xd6, 0xd0, 0xa6, 0xaa, 0x7c, 0xc9,
	0x6c, 0xd5, 0x99, 0x61, 0x0f, 0x8e, 0x67, 0x59, 0x21, 0xf7, 0x11, 0x96, 0x25, 0x5b, 0x62, 0xf8,
	0xc7, 0x06, 0xef, 0x06, 0xc5, 0x06, 0x85, 0xfa, 0x66, 0x24, 0x3d, 0xb0, 0xe7, 0xd3, 0x2a, 0xc8,
	0x9e, 0x4f, 0xc9, 0x7b, 0x70, 0x75, 0x43, 0x27, 0x75, 0xa9, 0x39, 0x90, 0x00, 0xbc, 0xc9, 0x5a,
	0x08, 0xcc, 0xe5, 0x2d, 0x8a, 0x4c, 0x67, 0xba, 0xb4, 0x29, 0x91, 0x01, 0x74, 0xee, 0xb9, 0xc4,
	0xf8, 0x27, 0x17, 0x55, 0xfe, 0xcb, 0x59, 0xf5, 0xae, 0x90, 0xc5, 0x28, 0xe6, 0x53, 0xdf, 0x35,
	0xbd, 0xe7, 0xb3, 0xde, 0xcc, 0xb3, 0x2c, 0x91, 0xf3, 0x3c, 0xc6, 0x9d, 0xdf, 0xae, 0x36, 0xd7,
	0x92, 0x72, 0x5c, 0xb1, 0x52, 0x5e, 0x16, 0x45, 0x9a, 0x60, 0xec, 0xbf, 0x31, 0x8e, 0x86, 0x44,
	0xce, 0x00, 0x22, 0x26, 0x17, 0x2b, 0xb3, 0xa2, 0x13, 0x38, 0x43, 0x97, 0x36, 0x14, 0x72, 0x0a,
	0xdd, 0x1c, 0x77, 0x55, 0x42, 0x57, 0xb7, 0x6b, 0x81, 0x7c, 0x02, 0x27, 0xe5, 0x4b, 0x1f, 0xf4,
	0xe5, 0x7a, 0x23, 0x8d, 0xce, 0x2c, 0x97, 0x62, 0x4f, 0x95, 0xfe, 0xed, 0x33, 0x40, 0x4d, 0x07,
	0x69, 0x83, 0x7d, 0xfd, 0xbb, 0x7f, 0x44, 0xba, 0xe0, 0xce, 0x28, 0xbd, 0xa6, 0x7d, 0x6b, 0xfc,
	0xd7, 0x02, 0x6f, 0xa2, 0x88, 0x88, 0x34, 0x11, 0xe4, 0x07, 0x1c, 0xdf, 0x15, 0x29, 0x67, 0x71,
	0x45, 0xcf, 0xc9, 0x2b, 0xbc, 0x0c, 0xde, 0xfd, 0x07, 0xc1, 0xf0, 0x88, 0x7c, 0x07, 0xef, 0xae,
	0x88, 0x99, 0x44, 0x83, 0xc2, 0x87, 0x03, 0xd7, 0x33, 0x21, 0xaf, 0x0d, 0x5f, 0x42, 0xe7, 0x17,
	0x4a, 0x73, 0x69, 0x1f, 0x0f, 0x2c, 0x4d, 0x0a, 0x06, 0xfe, 0xe1, 0x74, 0xcd, 0x43, 0x78, 0xf4,
	0xd0, 0xd6, 0xff, 0xcd, 0xc5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x89, 0xf2, 0xa4, 0x5f, 0x82,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaosMonkeyClient is the client API for ChaosMonkey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaosMonkeyClient interface {
	UploadMatrix(ctx context.Context, in *ConnMatrix, opts ...grpc.CallOption) (*Status, error)
	UpdateValue(ctx context.Context, in *MatValue, opts ...grpc.CallOption) (*Status, error)
	GetState(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServerState, error)
}

type chaosMonkeyClient struct {
	cc *grpc.ClientConn
}

func NewChaosMonkeyClient(cc *grpc.ClientConn) ChaosMonkeyClient {
	return &chaosMonkeyClient{cc}
}

func (c *chaosMonkeyClient) UploadMatrix(ctx context.Context, in *ConnMatrix, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/chaosmonkey.ChaosMonkey/UploadMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosMonkeyClient) UpdateValue(ctx context.Context, in *MatValue, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/chaosmonkey.ChaosMonkey/UpdateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosMonkeyClient) GetState(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*ServerState, error) {
	out := new(ServerState)
	err := c.cc.Invoke(ctx, "/chaosmonkey.ChaosMonkey/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaosMonkeyServer is the server API for ChaosMonkey service.
type ChaosMonkeyServer interface {
	UploadMatrix(context.Context, *ConnMatrix) (*Status, error)
	UpdateValue(context.Context, *MatValue) (*Status, error)
	GetState(context.Context, *EmptyMessage) (*ServerState, error)
}

func RegisterChaosMonkeyServer(s *grpc.Server, srv ChaosMonkeyServer) {
	s.RegisterService(&_ChaosMonkey_serviceDesc, srv)
}

func _ChaosMonkey_UploadMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnMatrix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosMonkeyServer).UploadMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chaosmonkey.ChaosMonkey/UploadMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosMonkeyServer).UploadMatrix(ctx, req.(*ConnMatrix))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosMonkey_UpdateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosMonkeyServer).UpdateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chaosmonkey.ChaosMonkey/UpdateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosMonkeyServer).UpdateValue(ctx, req.(*MatValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosMonkey_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosMonkeyServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chaosmonkey.ChaosMonkey/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosMonkeyServer).GetState(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChaosMonkey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chaosmonkey.ChaosMonkey",
	HandlerType: (*ChaosMonkeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadMatrix",
			Handler:    _ChaosMonkey_UploadMatrix_Handler,
		},
		{
			MethodName: "UpdateValue",
			Handler:    _ChaosMonkey_UpdateValue_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _ChaosMonkey_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chaosmonkey.proto",
}
