// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaosmonkey.proto

package chaosmonkey

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK    StatusCode = 0
	StatusCode_ERROR StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var StatusCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{0}
}

type Status struct {
	Ret                  StatusCode `protobuf:"varint,1,opt,name=ret,proto3,enum=chaosmonkey.StatusCode" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetRet() StatusCode {
	if m != nil {
		return m.Ret
	}
	return StatusCode_OK
}

type ConnMatrix struct {
	Rows                 []*ConnMatrix_MatRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	From                 int32                `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnMatrix) Reset()         { *m = ConnMatrix{} }
func (m *ConnMatrix) String() string { return proto.CompactTextString(m) }
func (*ConnMatrix) ProtoMessage()    {}
func (*ConnMatrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{1}
}

func (m *ConnMatrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMatrix.Unmarshal(m, b)
}
func (m *ConnMatrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMatrix.Marshal(b, m, deterministic)
}
func (m *ConnMatrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMatrix.Merge(m, src)
}
func (m *ConnMatrix) XXX_Size() int {
	return xxx_messageInfo_ConnMatrix.Size(m)
}
func (m *ConnMatrix) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMatrix.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMatrix proto.InternalMessageInfo

func (m *ConnMatrix) GetRows() []*ConnMatrix_MatRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *ConnMatrix) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

type ConnMatrix_MatRow struct {
	Vals                 []float32 `protobuf:"fixed32,1,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnMatrix_MatRow) Reset()         { *m = ConnMatrix_MatRow{} }
func (m *ConnMatrix_MatRow) String() string { return proto.CompactTextString(m) }
func (*ConnMatrix_MatRow) ProtoMessage()    {}
func (*ConnMatrix_MatRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{1, 0}
}

func (m *ConnMatrix_MatRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMatrix_MatRow.Unmarshal(m, b)
}
func (m *ConnMatrix_MatRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMatrix_MatRow.Marshal(b, m, deterministic)
}
func (m *ConnMatrix_MatRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMatrix_MatRow.Merge(m, src)
}
func (m *ConnMatrix_MatRow) XXX_Size() int {
	return xxx_messageInfo_ConnMatrix_MatRow.Size(m)
}
func (m *ConnMatrix_MatRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMatrix_MatRow.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMatrix_MatRow proto.InternalMessageInfo

func (m *ConnMatrix_MatRow) GetVals() []float32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

type MatValue struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Val                  float32  `protobuf:"fixed32,3,opt,name=val,proto3" json:"val,omitempty"`
	From                 int32    `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatValue) Reset()         { *m = MatValue{} }
func (m *MatValue) String() string { return proto.CompactTextString(m) }
func (*MatValue) ProtoMessage()    {}
func (*MatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ee19988c9499698, []int{2}
}

func (m *MatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatValue.Unmarshal(m, b)
}
func (m *MatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatValue.Marshal(b, m, deterministic)
}
func (m *MatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatValue.Merge(m, src)
}
func (m *MatValue) XXX_Size() int {
	return xxx_messageInfo_MatValue.Size(m)
}
func (m *MatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MatValue.DiscardUnknown(m)
}

var xxx_messageInfo_MatValue proto.InternalMessageInfo

func (m *MatValue) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *MatValue) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *MatValue) GetVal() float32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *MatValue) GetFrom() int32 {
	if m != nil {
		return m.From
	}
	return 0
}

func init() {
	proto.RegisterEnum("chaosmonkey.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "chaosmonkey.Status")
	proto.RegisterType((*ConnMatrix)(nil), "chaosmonkey.ConnMatrix")
	proto.RegisterType((*ConnMatrix_MatRow)(nil), "chaosmonkey.ConnMatrix.MatRow")
	proto.RegisterType((*MatValue)(nil), "chaosmonkey.MatValue")
}

func init() { proto.RegisterFile("chaosmonkey.proto", fileDescriptor_3ee19988c9499698) }

var fileDescriptor_3ee19988c9499698 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x97, 0xfe, 0x42, 0x5f, 0x45, 0x6a, 0x44, 0x56, 0x86, 0x68, 0xe9, 0xa9, 0x7a, 0xe8,
	0xa1, 0x3b, 0x0a, 0x5e, 0x8a, 0x27, 0x29, 0x83, 0xe8, 0xbc, 0xc7, 0xb5, 0xa2, 0x98, 0xf5, 0x95,
	0x34, 0x5b, 0xf5, 0x5f, 0xf0, 0xaf, 0x96, 0xa4, 0xd3, 0x6e, 0xb0, 0xdd, 0xbe, 0xbc, 0x7c, 0xde,
	0x7b, 0xf9, 0x24, 0x70, 0xb6, 0x78, 0xe7, 0xd8, 0x2e, 0xb1, 0xfe, 0xac, 0xbe, 0xd3, 0x46, 0xa2,
	0x42, 0xea, 0x6f, 0x95, 0xe2, 0x29, 0x78, 0x4f, 0x8a, 0xab, 0x55, 0x4b, 0x6f, 0xc0, 0x96, 0x95,
	0x0a, 0x49, 0x44, 0x92, 0xd3, 0x6c, 0x9c, 0x6e, 0xf7, 0xf5, 0x44, 0x8e, 0x65, 0xc5, 0x34, 0x13,
	0x4b, 0x80, 0x1c, 0xeb, 0xba, 0xe0, 0x4a, 0x7e, 0x7c, 0xd1, 0x0c, 0x1c, 0x89, 0x5d, 0x1b, 0x92,
	0xc8, 0x4e, 0xfc, 0xec, 0x6a, 0xa7, 0x73, 0xc0, 0xd2, 0x82, 0x2b, 0x86, 0x1d, 0x33, 0x2c, 0xa5,
	0xe0, 0xbc, 0x49, 0x5c, 0x86, 0x56, 0x44, 0x12, 0x97, 0x99, 0x3c, 0xb9, 0x04, 0xaf, 0x67, 0xf4,
	0xe9, 0x9a, 0x8b, 0x7e, 0xa2, 0xc5, 0x4c, 0x8e, 0x9f, 0xe1, 0xa8, 0xe0, 0xea, 0x85, 0x8b, 0x55,
	0x45, 0x03, 0xb0, 0x25, 0x76, 0xe6, 0xaa, 0x2e, 0xd3, 0x51, 0x57, 0x16, 0x28, 0x36, 0xe3, 0x74,
	0xd4, 0x95, 0x35, 0x17, 0xa1, 0x1d, 0x91, 0xc4, 0x62, 0x3a, 0xfe, 0xef, 0x74, 0x86, 0x9d, 0xb7,
	0xd7, 0x00, 0x83, 0x1c, 0xf5, 0xc0, 0x9a, 0x3d, 0x06, 0x23, 0x7a, 0x0c, 0xee, 0x03, 0x63, 0x33,
	0x16, 0x90, 0xec, 0x87, 0x80, 0x9f, 0x6b, 0xa1, 0xc2, 0x08, 0xd1, 0x7b, 0x38, 0x99, 0x37, 0x02,
	0x79, 0xb9, 0x91, 0x1f, 0x1f, 0xd0, 0x9d, 0x9c, 0xef, 0x79, 0xc1, 0x78, 0x44, 0xef, 0xc0, 0x9f,
	0x37, 0x25, 0x57, 0x55, 0x6f, 0x72, 0xb1, 0x43, 0xfd, 0x09, 0x1e, 0x68, 0x7e, 0xf5, 0xcc, 0x07,
	0x4e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x75, 0x34, 0x5c, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaosMonkeyClient is the client API for ChaosMonkey service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaosMonkeyClient interface {
	UploadMatrix(ctx context.Context, in *ConnMatrix, opts ...grpc.CallOption) (*Status, error)
	UpdateValue(ctx context.Context, in *MatValue, opts ...grpc.CallOption) (*Status, error)
}

type chaosMonkeyClient struct {
	cc *grpc.ClientConn
}

func NewChaosMonkeyClient(cc *grpc.ClientConn) ChaosMonkeyClient {
	return &chaosMonkeyClient{cc}
}

func (c *chaosMonkeyClient) UploadMatrix(ctx context.Context, in *ConnMatrix, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/chaosmonkey.ChaosMonkey/UploadMatrix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaosMonkeyClient) UpdateValue(ctx context.Context, in *MatValue, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/chaosmonkey.ChaosMonkey/UpdateValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChaosMonkeyServer is the server API for ChaosMonkey service.
type ChaosMonkeyServer interface {
	UploadMatrix(context.Context, *ConnMatrix) (*Status, error)
	UpdateValue(context.Context, *MatValue) (*Status, error)
}

// UnimplementedChaosMonkeyServer can be embedded to have forward compatible implementations.
type UnimplementedChaosMonkeyServer struct {
}

func (*UnimplementedChaosMonkeyServer) UploadMatrix(ctx context.Context, req *ConnMatrix) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadMatrix not implemented")
}
func (*UnimplementedChaosMonkeyServer) UpdateValue(ctx context.Context, req *MatValue) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateValue not implemented")
}

func RegisterChaosMonkeyServer(s *grpc.Server, srv ChaosMonkeyServer) {
	s.RegisterService(&_ChaosMonkey_serviceDesc, srv)
}

func _ChaosMonkey_UploadMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnMatrix)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosMonkeyServer).UploadMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chaosmonkey.ChaosMonkey/UploadMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosMonkeyServer).UploadMatrix(ctx, req.(*ConnMatrix))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChaosMonkey_UpdateValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaosMonkeyServer).UpdateValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chaosmonkey.ChaosMonkey/UpdateValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaosMonkeyServer).UpdateValue(ctx, req.(*MatValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChaosMonkey_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chaosmonkey.ChaosMonkey",
	HandlerType: (*ChaosMonkeyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadMatrix",
			Handler:    _ChaosMonkey_UploadMatrix_Handler,
		},
		{
			MethodName: "UpdateValue",
			Handler:    _ChaosMonkey_UpdateValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chaosmonkey.proto",
}
