// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaosmonkey/chaosmonkey.proto

package chaosmonkey

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK    StatusCode = 0
	StatusCode_ERROR StatusCode = 1
)

var StatusCode_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var StatusCode_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_46a95c2c71ca5876, []int{0}
}

type Status struct {
	Ret                  StatusCode `protobuf:"varint,1,opt,name=ret,proto3,enum=chaosmonkey.StatusCode" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a95c2c71ca5876, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetRet() StatusCode {
	if m != nil {
		return m.Ret
	}
	return StatusCode_OK
}

type ConnMatrix struct {
	Rows                 []*ConnMatrix_MatRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConnMatrix) Reset()         { *m = ConnMatrix{} }
func (m *ConnMatrix) String() string { return proto.CompactTextString(m) }
func (*ConnMatrix) ProtoMessage()    {}
func (*ConnMatrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a95c2c71ca5876, []int{1}
}

func (m *ConnMatrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMatrix.Unmarshal(m, b)
}
func (m *ConnMatrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMatrix.Marshal(b, m, deterministic)
}
func (m *ConnMatrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMatrix.Merge(m, src)
}
func (m *ConnMatrix) XXX_Size() int {
	return xxx_messageInfo_ConnMatrix.Size(m)
}
func (m *ConnMatrix) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMatrix.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMatrix proto.InternalMessageInfo

func (m *ConnMatrix) GetRows() []*ConnMatrix_MatRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type ConnMatrix_MatRow struct {
	Vals                 []float32 `protobuf:"fixed32,1,rep,packed,name=vals,proto3" json:"vals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConnMatrix_MatRow) Reset()         { *m = ConnMatrix_MatRow{} }
func (m *ConnMatrix_MatRow) String() string { return proto.CompactTextString(m) }
func (*ConnMatrix_MatRow) ProtoMessage()    {}
func (*ConnMatrix_MatRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a95c2c71ca5876, []int{1, 0}
}

func (m *ConnMatrix_MatRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMatrix_MatRow.Unmarshal(m, b)
}
func (m *ConnMatrix_MatRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMatrix_MatRow.Marshal(b, m, deterministic)
}
func (m *ConnMatrix_MatRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMatrix_MatRow.Merge(m, src)
}
func (m *ConnMatrix_MatRow) XXX_Size() int {
	return xxx_messageInfo_ConnMatrix_MatRow.Size(m)
}
func (m *ConnMatrix_MatRow) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMatrix_MatRow.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMatrix_MatRow proto.InternalMessageInfo

func (m *ConnMatrix_MatRow) GetVals() []float32 {
	if m != nil {
		return m.Vals
	}
	return nil
}

type MatValue struct {
	Row                  int32    `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col                  int32    `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Val                  float32  `protobuf:"fixed32,3,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MatValue) Reset()         { *m = MatValue{} }
func (m *MatValue) String() string { return proto.CompactTextString(m) }
func (*MatValue) ProtoMessage()    {}
func (*MatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a95c2c71ca5876, []int{2}
}

func (m *MatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatValue.Unmarshal(m, b)
}
func (m *MatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatValue.Marshal(b, m, deterministic)
}
func (m *MatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatValue.Merge(m, src)
}
func (m *MatValue) XXX_Size() int {
	return xxx_messageInfo_MatValue.Size(m)
}
func (m *MatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MatValue.DiscardUnknown(m)
}

var xxx_messageInfo_MatValue proto.InternalMessageInfo

func (m *MatValue) GetRow() int32 {
	if m != nil {
		return m.Row
	}
	return 0
}

func (m *MatValue) GetCol() int32 {
	if m != nil {
		return m.Col
	}
	return 0
}

func (m *MatValue) GetVal() float32 {
	if m != nil {
		return m.Val
	}
	return 0
}

func init() {
	proto.RegisterEnum("chaosmonkey.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Status)(nil), "chaosmonkey.Status")
	proto.RegisterType((*ConnMatrix)(nil), "chaosmonkey.ConnMatrix")
	proto.RegisterType((*ConnMatrix_MatRow)(nil), "chaosmonkey.ConnMatrix.MatRow")
	proto.RegisterType((*MatValue)(nil), "chaosmonkey.MatValue")
}

func init() { proto.RegisterFile("chaosmonkey/chaosmonkey.proto", fileDescriptor_46a95c2c71ca5876) }

var fileDescriptor_46a95c2c71ca5876 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x14, 0xc4, 0xbb, 0x49, 0x1b, 0xf4, 0x45, 0x24, 0xac, 0x48, 0x43, 0xf1, 0x4f, 0xc8, 0x29, 0x7a,
	0x88, 0x90, 0x1e, 0x05, 0x11, 0x82, 0x27, 0x09, 0x85, 0x95, 0x7a, 0x14, 0x9e, 0x49, 0x40, 0x71,
	0xcd, 0x0b, 0xc9, 0xb6, 0xd1, 0xaf, 0xe0, 0xa7, 0x96, 0xcd, 0x2a, 0x4d, 0xa1, 0xbd, 0xcd, 0x0e,
	0x33, 0xf0, 0x9b, 0x7d, 0x70, 0x9e, 0xbf, 0x21, 0xb5, 0x9f, 0x54, 0x7d, 0x94, 0xdf, 0x37, 0x03,
	0x1d, 0xd7, 0x0d, 0x29, 0xe2, 0xee, 0xc0, 0x0a, 0xe7, 0xe0, 0x3c, 0x29, 0x54, 0xab, 0x96, 0x5f,
	0x81, 0xdd, 0x94, 0xca, 0x67, 0x01, 0x8b, 0x8e, 0x93, 0x69, 0x3c, 0xec, 0x99, 0x44, 0x4a, 0x45,
	0x29, 0x74, 0x26, 0x7c, 0x01, 0x48, 0xa9, 0xaa, 0x32, 0x54, 0xcd, 0xfb, 0x17, 0x4f, 0x60, 0xdc,
	0x50, 0xd7, 0xfa, 0x2c, 0xb0, 0x23, 0x37, 0xb9, 0xd8, 0x6a, 0x6e, 0x62, 0x71, 0x86, 0x4a, 0x50,
	0x27, 0xfa, 0xec, 0xec, 0x0c, 0x1c, 0xf3, 0xe6, 0x1c, 0xc6, 0x6b, 0x94, 0xa6, 0x6d, 0x89, 0x5e,
	0x87, 0xf7, 0x70, 0x90, 0xa1, 0x7a, 0x46, 0xb9, 0x2a, 0xb9, 0x07, 0x76, 0x43, 0x5d, 0x8f, 0x35,
	0x11, 0x5a, 0x6a, 0x27, 0x27, 0xe9, 0x5b, 0xc6, 0xc9, 0x49, 0x6a, 0x67, 0x8d, 0xd2, 0xb7, 0x03,
	0x16, 0x59, 0x42, 0xcb, 0xeb, 0x4b, 0x80, 0x0d, 0x34, 0x77, 0xc0, 0x5a, 0x3c, 0x7a, 0x23, 0x7e,
	0x08, 0x93, 0x07, 0x21, 0x16, 0xc2, 0x63, 0xc9, 0x0f, 0x03, 0x37, 0xd5, 0xa0, 0x59, 0x0f, 0xca,
	0xef, 0xe0, 0x68, 0x59, 0x4b, 0xc2, 0xe2, 0x6f, 0xd4, 0x74, 0xcf, 0x8c, 0xd9, 0xc9, 0x8e, 0x9f,
	0x09, 0x47, 0xfc, 0x16, 0xdc, 0x65, 0x5d, 0xa0, 0x2a, 0x0d, 0xf5, 0xe9, 0x56, 0xea, 0x7f, 0xcc,
	0x9e, 0xf2, 0xab, 0xd3, 0x1f, 0x66, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xe5, 0xe2, 0x0e,
	0xb9, 0x01, 0x00, 0x00,
}
