// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kvstore/kvstore.proto

package kvstore

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// You'll likely need to define more specific return codes than these!
type ReturnCode int32

const (
	ReturnCode_SUCCESS ReturnCode = 0
	ReturnCode_FAILURE ReturnCode = 1
)

var ReturnCode_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var ReturnCode_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x ReturnCode) String() string {
	return proto.EnumName(ReturnCode_name, int32(x))
}

func (ReturnCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00328f6d75b13733, []int{0}
}

type GetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00328f6d75b13733, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value                string     `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ret                  ReturnCode `protobuf:"varint,2,opt,name=ret,proto3,enum=kvstore.ReturnCode" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00328f6d75b13733, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetResponse) GetRet() ReturnCode {
	if m != nil {
		return m.Ret
	}
	return ReturnCode_SUCCESS
}

type PutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00328f6d75b13733, []int{2}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResponse struct {
	Ret                  ReturnCode `protobuf:"varint,1,opt,name=ret,proto3,enum=kvstore.ReturnCode" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00328f6d75b13733, []int{3}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetRet() ReturnCode {
	if m != nil {
		return m.Ret
	}
	return ReturnCode_SUCCESS
}

func init() {
	proto.RegisterEnum("kvstore.ReturnCode", ReturnCode_name, ReturnCode_value)
	proto.RegisterType((*GetRequest)(nil), "kvstore.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "kvstore.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "kvstore.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "kvstore.PutResponse")
}

func init() { proto.RegisterFile("kvstore/kvstore.proto", fileDescriptor_00328f6d75b13733) }

var fileDescriptor_00328f6d75b13733 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x2e, 0x2b, 0x2e,
	0xc9, 0x2f, 0x4a, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x1c, 0x17, 0x97, 0x7b, 0x6a, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00,
	0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0xa9, 0xe4, 0xc5,
	0xc5, 0x0d, 0x96, 0x2f, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc,
	0x29, 0x4d, 0x85, 0x2a, 0x81, 0x70, 0x84, 0x54, 0xb9, 0x98, 0x8b, 0x52, 0x4b, 0x24, 0x98, 0x14,
	0x18, 0x35, 0xf8, 0x8c, 0x84, 0xf5, 0x60, 0x56, 0x05, 0xa5, 0x96, 0x94, 0x16, 0xe5, 0x39, 0xe7,
	0xa7, 0xa4, 0x06, 0x81, 0xe4, 0x95, 0x4c, 0xb8, 0xb8, 0x02, 0x4a, 0x71, 0xdb, 0x85, 0x30, 0x9c,
	0x09, 0xc9, 0x70, 0x25, 0x13, 0x2e, 0x6e, 0xb0, 0x2e, 0xa8, 0x0b, 0xa0, 0x76, 0x31, 0xe2, 0xb7,
	0x4b, 0x4b, 0x8d, 0x8b, 0x0b, 0x21, 0x24, 0xc4, 0xcd, 0xc5, 0x1e, 0x1c, 0xea, 0xec, 0xec, 0x1a,
	0x1c, 0x2c, 0xc0, 0x00, 0xe2, 0xb8, 0x39, 0x7a, 0xfa, 0x84, 0x06, 0xb9, 0x0a, 0x30, 0x1a, 0x95,
	0x73, 0xf1, 0x7a, 0xa7, 0x56, 0x86, 0x81, 0x6c, 0x0a, 0x06, 0x19, 0x24, 0x64, 0xc4, 0xc5, 0xec,
	0x9e, 0x5a, 0x22, 0x84, 0x30, 0x19, 0x11, 0x3c, 0x52, 0x22, 0xa8, 0x82, 0x10, 0x17, 0x29, 0x31,
	0x80, 0xf4, 0x04, 0x94, 0x22, 0xeb, 0x41, 0x78, 0x13, 0x49, 0x0f, 0x92, 0x2f, 0x94, 0x18, 0x92,
	0xd8, 0xc0, 0x11, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x09, 0x22, 0x82, 0xa1, 0x01,
	0x00, 0x00,
}
